### ISSUE TITLE
No battery low notification if the charger is disconnected while the battery was lower than low_pct

### ISSUE THREAD

**Issue by salman-farooq-sh** [cdown/battery-notify#79]
I tried to fix it myself and submit a PR but it seems that https://github.com/cdown/battery-notify/blob/6fe268dc6eb1578bdf02e938ccb6ba916e1c2304/src/main.rs#L123 is reached in this scenario (I tested by adding an info!() and checking the logs) but the notification doesn't display for some reason.

Other notifications show without problem.

**Comment by salman-farooq-sh** [comment]
I have narrowed it down to this: if any notification is triggered with the same summary, it doesn't show again until a restart. Like in this case. The issue is here:

https://github.com/cdown/battery-notify/blob/6fe268dc6eb1578bdf02e938ccb6ba916e1c2304/src/notification.rs#L12

It allows for notifications only with a new summary, but the user can close a notification and want it to appear again later with the same summary.

**Comment by cdown** [comment]
Untested, but I think c85f138f889d81aeffe4dd98c3c82a9bb45590e6 should fix it. Could you give it a try? :-)

**Comment by salman-farooq-sh** [comment]
It seems like it works! But why isn't there a new notification on every interval?

**Comment by cdown** [comment]
Creating a new notification every interval isn't a good user experience. Depending on how the notification system or the user's environment handles repeated notifications, it might appear as a single alert being refreshed, which could be acceptable. However, it might also result in what seems like a new alert each time, especially if an event is fired over D-Bus or other mechanisms that don't support cancellation or replacement of notifications.

So the goal here is to create one notification for a particular notification type when the condition is first reached, and only update it again when the notification reaches a new criticality (like low -> critical)

**Comment by salman-farooq-sh** [comment]
Definitely. You are completely right.

But I meant to ask in the sense that I don't understand the code. To me it seems like a new notification _should_ be created as the code is written right now, but somehow it does not do that so I am obviously wrong. Can you please explain it to me? Thanks a lot! I want to incorporate this into my PR. You can answer this in the PR review too if you want or if you see anything I could have done better there.

**Comment by cdown** [comment]
It isn't created again because, in that case, `self.summary == summary`, so we forego any creation :-)

This is the current code that handles that:

https://github.com/cdown/battery-notify/blob/master/src/notification.rs#L12
